# Generated by Django 6.0.6 on 2026-07-02 21:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duree_jours', models.PositiveIntegerField(default=30)),
                ('avantages', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('renouvellement_automatique', models.BooleanField(default=False)),
                ('date_renouvellement', models.DateTimeField(blank=True, null=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='abonnementVendeur.planabonnement')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(default='en_attente', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='abonnementVendeur.abonnement')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_abonnement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
