# Generated by Django 6.0.6 on 2026-07-02 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnementVendeur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('carte', 'Carte bancaire'), ('paypal', 'PayPal'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], default='carte', max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payé', 'Payé'), ('échoué', 'Échoué'), ('annulé', 'Annulé')], default='en_attente', max_length=50)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('commande_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_generaux', to='abonnementVendeur.abonnement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=50)),
                ('nouveau_statut', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('date_maj', models.DateTimeField(default=django.utils.timezone.now)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='paiement.paiement')),
            ],
            options={
                'verbose_name': 'Historique de paiement',
                'verbose_name_plural': 'Historiques de paiement',
                'ordering': ['-date_maj'],
            },
        ),
    ]
